### ISSUE TITLE
Inner Pages: Unstyled unordered list.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Hollywood-Kitchens#1]
![image](https://cloud.githubusercontent.com/assets/13363508/16574775/180eec3a-42b5-11e6-86a5-7b56650ac671.png)
![image](https://cloud.githubusercontent.com/assets/13363508/16574824/b5999a68-42b5-11e6-887f-cf8b1dd1318e.png)

**Comment by zackneron** [comment]
Back End Dev need to wrap the li with <ul>
