### ISSUE TITLE
Header: broken style submenu

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Hollywood-Kitchens#107]
![image](https://cloud.githubusercontent.com/assets/17717843/16577128/f10410a0-42c5-11e6-92b5-f6911bded9cd.png)

See video link to repro the issue:
http://screencast.com/t/lmHV2Puv0t6

**Comment by iteano** [comment]
Still not fixed.
![image](https://cloud.githubusercontent.com/assets/18256652/17206831/3b7aa358-54e4-11e6-8aeb-01deb7cb49da.png)
