### ISSUE TITLE
Home - leadins: Incorrect height set for the images.  A difference of more than 30px is too much.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hollywood-Kitchens#111]
There are no other images in the lead-ins section.  And if you take a look at the design, you can see the difference in the image height.
![image](https://cloud.githubusercontent.com/assets/11186313/17281211/30c1ae98-57cd-11e6-937a-8953d972af9e.png)

**Comment by euveng** [comment]
Issue needs to be described in more detail.

**Comment by euveng** [comment]
Fixed.
