### ISSUE TITLE
Product Single : At 767px, gallery thumbnails are too big, seems bigger than featured images which makes its resolution blurry.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Hollywood-Kitchens#114]
![image](https://cloud.githubusercontent.com/assets/18256652/16577307/f8c2ed74-42c6-11e6-80d6-775c3528b30a.png)

**Comment by euveng** [comment]
Changed to a different thumbnail size so the thumbnails are no longer blur.

**Comment by euveng** [comment]
I have changed 2 thumbnails in a row to 3 in a row, so that it doesn't need to be stretched out too much. is this ok?
