### ISSUE TITLE
Testimonials: It must be custom post for testimonials as per the scope not repeater 

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Hollywood-Kitchens#13]
![image](https://cloud.githubusercontent.com/assets/18568310/16575036/65c3d510-42b7-11e6-8712-082039a34810.png)

**Comment by titandigitalaus** [comment]
As part of the new base framework, testimonials will now be a repeater field instead of custom post type. Flagging this as scope error.

**Comment by roseliesromeo** [comment]
FYI: This is using the old build.

**Comment by euveng** [comment]
This base framework version (and 1 or 2 versions before this one) has started using acf instead of custom post type for the testimonial. This is not a valid issue please.
