### ISSUE TITLE
Gallery: Hover state behaviour isn't implemented.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Hollywood-Kitchens#14]
![image](https://cloud.githubusercontent.com/assets/13363508/16575041/74ea684c-42b7-11e6-9791-2552b3bbb303.png)

**Comment by roseliesromeo** [comment]
No hover state applied for the gallery images in the single page.
![image](https://cloud.githubusercontent.com/assets/11186313/17207259/50fac800-54e6-11e6-9e9a-b2afe2b3ff39.png)

**Comment by zackneron** [comment]
Was not award there will be single page for gallery.
What do you mean by 'Hover state style is inconsistent with the given design.'? On hover it should zoom in and the background color to be a transparent green.
