### ISSUE TITLE
News - Width of the image should be 270px as per design.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Hollywood-Kitchens#17]
![image](https://cloud.githubusercontent.com/assets/18587097/16575068/55a20952-42af-11e6-8722-03fb45bf0b48.png)

**Comment by euveng** [comment]
The image width should be allowed to follow the bootstrap grid, so understandably there will be some deviation. In this case, the deviation looks to be under 10px so it should not be flagged in the first place.
