### ISSUE TITLE
Contact Us: The form layout implemented did not follow the given design.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hollywood-Kitchens#24]
![image](https://cloud.githubusercontent.com/assets/12888048/16575145/53f2f842-42b8-11e6-8d6f-ad01d781daa2.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16575153/666ea372-42b8-11e6-8126-49974ea5b3bd.png)

**Comment by roseliesromeo** [comment]
Submit button is supposed to be beside CAPTCHA as per mock.
![image](https://cloud.githubusercontent.com/assets/11186313/17207347/c369f69a-54e6-11e6-8e56-69ed0ab2b9be.png)

**Comment by zackneron** [comment]
This is a design error - the button is in a gform_footer div that shouldn't overlap with the inputs in the gform_body div
