### ISSUE TITLE
Contact Us: W3C Error

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hollywood-Kitchens#3]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fhollywoodkitchens-imp.stage.titanweb.com.au%2Fcontact-us%2F

![image](https://cloud.githubusercontent.com/assets/12888048/16574809/849a20f4-42b5-11e6-8563-be4cf90e7bcb.png)

**Comment by euveng** [comment]
This markup is generated by gravity forms and cannot be changed duringimplementation.
