### ISSUE TITLE
All Inner Pages: Heading use for page title was H2. It should be H1

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hollywood-Kitchens#32]
Note: Follow the correct styling for H1 in the given design

![image](https://cloud.githubusercontent.com/assets/12888048/16575207/f345307c-42b8-11e6-88cd-f4a0ea0bb7ad.png)

**Comment by roseliesromeo** [comment]
Not fixed for single pages:
News single
Services single
Products single
