### ISSUE TITLE
Home - contact us section: Opening Hours isn't from the business details.  Showroom Opening Hours is still displayed even if Monday to Friday field is empty. It is from the another acf instead.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hollywood-Kitchens#34]
![image](https://cloud.githubusercontent.com/assets/11186313/16575245/4237f1f6-42b9-11e6-841c-68ce934cc4f9.png)

![image](https://cloud.githubusercontent.com/assets/11186313/16576034/1778264c-42bf-11e6-8a44-87205cb1df2f.png)

**Comment by euveng** [comment]
Fixed.
