### ISSUE TITLE
Product Single : Center align instead of top left align the images on its container.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Hollywood-Kitchens#37]
![image](https://cloud.githubusercontent.com/assets/18256652/16575253/599a76fc-42b9-11e6-96cd-934c9d4cf517.png)

**Comment by euveng** [comment]
Is this issue still valid?

**Comment by roseliesromeo** [comment]
![image](https://cloud.githubusercontent.com/assets/11186313/17281892/50955e72-57d2-11e6-98b1-056816ade672.png)

**Comment by roseliesromeo** [comment]
No change made.   Are you sure fixes are pushed to staging?
![image](https://cloud.githubusercontent.com/assets/11186313/17322873/5107dbc2-58d2-11e6-990e-0f7713f39864.png)
