### ISSUE TITLE
Home - prefooter form: Lacking mail icon from the Send Enquiry button.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hollywood-Kitchens#50]
![image](https://cloud.githubusercontent.com/assets/11186313/16575444/d2722682-42ba-11e6-82e4-a8e42855a99d.png)

**Comment by roseliesromeo** [comment]
Incorrect icon displayed. Instead of mail icon, it shows right arrow.

**Comment by euveng** [comment]
This needs to be consistent with the contact us submit button. This is because there is only one global function that sets the icon for all forms throughout the site. Flagging this as design error.
