### ISSUE TITLE
Gallery: Why are you not using the fancybox plugin as the scope mentioned? Currently it is using the fresco lightbox.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Hollywood-Kitchens#53]
![image](https://cloud.githubusercontent.com/assets/13363508/16575372/406d8c4a-42ba-11e6-8174-e14d3c2da30c.png)

**Comment by euveng** [comment]
Part of the new base framework. Will not fix.

**Comment by roseliesromeo** [comment]
It now opens in fancy box.
