### ISSUE TITLE
Gallery: Space gap in between images isn't matched as per design.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Hollywood-Kitchens#62]
![image](https://cloud.githubusercontent.com/assets/13363508/16575587/0cc26d50-42bc-11e6-932b-f93916227dd2.png)

**Comment by zackneron** [comment]
Why do we have title on each image for the gallery?

**Comment by euveng** [comment]
The original design was a single gallery page, so titles were not needed. There was a change request to have galleries as custom post types, so titles are now needed on each featured image on the main gallery listing page to link to gallery singles. Will not fix.

**Comment by roseliesromeo** [comment]
Seems fixed in the gallery single pages.
http://hollywoodkitchens-imp.stage.titanweb.com.au/gallery/kitchens/
