### ISSUE TITLE
Gallery - Responsive Checking: Too big empty space in the RHS in 767px viewport 'til the affected resolution.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Hollywood-Kitchens#67]
![image](https://cloud.githubusercontent.com/assets/13363508/16575632/5e6b44b0-42bc-11e6-80c9-2537f0e5729b.png)

**Comment by euveng** [comment]
Is this issue still valid now?

**Comment by roseliesromeo** [comment]
Display in two columns from in 480 - 991 resolutions.
![image](https://cloud.githubusercontent.com/assets/11186313/17281421/fe0be5fc-57ce-11e6-929c-8767aa1779ba.png)

**Comment by roseliesromeo** [comment]
![image](https://cloud.githubusercontent.com/assets/11186313/17322747/95e02c3c-58d1-11e6-9f23-9e80225d00b2.png)

**Comment by roseliesromeo** [comment]
Image is not centered below 480px.
![image](https://cloud.githubusercontent.com/assets/11186313/17352428/11dcf45e-5969-11e6-843a-6f6a5bc19396.png)

**Comment by euveng** [comment]
Fixed.
