### ISSUE TITLE
Home - leadins: Per scope, repeater should have a maximum and minimum of 4 rows only.  Currently, user is able to add more rows.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hollywood-Kitchens#73]
![image](https://cloud.githubusercontent.com/assets/11186313/16575897/40981e02-42be-11e6-83ce-12fca6dc379b.png)

**Comment by euveng** [comment]
This is a limitation on the titan toolbox core plugin and cannot be changed for this implementation. A workaround has been applied in the page template to limit the leadins to 4.
