### ISSUE TITLE
News(single) - Width of image should be 871px as per design.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Hollywood-Kitchens#84]
![image](https://cloud.githubusercontent.com/assets/18587097/16576352/ca35ede8-42b8-11e6-830e-1f09ec6ad035.png)

**Comment by zackneron** [comment]
We can't overwrite the original size of the image, which will result to image being stretched and blurry.
Per design the image should be 871/451 and the above is 720/960
