### ISSUE TITLE
Products : Misaligned page when featured image is set.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Hollywood-Kitchens#85]
![image](https://cloud.githubusercontent.com/assets/18256652/16576504/39baa6aa-42c2-11e6-962e-12b08759d738.png)

**Comment by euveng** [comment]
Looks fine here http://hollywoodkitchens-imp.stage.titanweb.com.au/products/.

**Comment by iteano** [comment]
Removing invalid, this is fixed as verified.
