### ISSUE TITLE
Contact Us: If fields for contact details are blank, do not display the respective heading for that specific field

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hollywood-Kitchens#86]
![image](https://cloud.githubusercontent.com/assets/12888048/16576562/912cfbcc-42c2-11e6-828c-172284882539.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16576590/b61b92ae-42c2-11e6-858e-9b2d352b5697.png)

**Comment by euveng** [comment]
Fixed.
