### ISSUE TITLE
Error Page: Sidebar was not implemented on error page

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hollywood-Kitchens#90]
![image](https://cloud.githubusercontent.com/assets/12888048/16576655/2fc20250-42c3-11e6-84cd-8809e6ff6066.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16576657/314f918c-42c3-11e6-9a4a-415f1e14ee7d.png)

**Comment by euveng** [comment]
Fixed.
