### ISSUE TITLE
Home - gallery: Images are pixelated in 767px resolution and below.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hollywood-Kitchens#92]
![image](https://cloud.githubusercontent.com/assets/11186313/16576718/993db3aa-42c3-11e6-9994-7e0218dc5c84.png)

**Comment by n-techawandee** [comment]
I've made the 2 column for 767 Layout

**Comment by iteano** [comment]
Images are still pixelated.

**Comment by euveng** [comment]
It looks fine at 768px. But I agree that it looks blurred between 480-767px. Are you suggesting that we should use 2 columns instead of 1 column at 480-767px?

**Comment by roseliesromeo** [comment]
Yes please.
